---
- name: Default instace configureation
  hosts: all
  become: yes

  roles:
   - main
  

- name: Bild configuration
  hosts: bild
  become: yes

  roles:
   - build

- name: Start prod container
  hosts: prod
  become: yes

  roles:
    - prod