---
- name: Default instace configureation
  hosts: all
  become: yes

  roles:
   - main
  vars_files:
   - ./main/vars/main.yml

- name: Bild configureation
  hosts: bild
  become: yes

  roles:
   - build